apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ping-server
spec:
  selector:
    matchLabels:
      app: ping-server
  serviceName: ping-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ping-server
    spec:
      containers:
      - name: ping-server
        image: mcr.microsoft.com/powershell:latest
        command: ["pwsh", "/scripts/loop.ps1"]
        workingDir: /scripts
        ports:
        - containerPort: 44
          name: ping
        volumeMounts:
        - name: config-volume
          mountPath: /scripts
      volumes:
        - name: config-volume
          configMap:
            name: ps1-scripts