apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ $.Release.Name }}-server
  name: {{ $.Release.Name }}-server
spec:
  ports:
  - port: 44
    name: ping
    protocol: UDP
    targetPort: 44
  selector:
    app: {{ $.Release.Name }}-server