apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-server
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-server
  serviceName: ping-server
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-server
    spec:
      containers:
      - name: ping-server
        image: mcr.microsoft.com/powershell:latest
        command: ["pwsh", "latency-check.ps1", "-server", "-listenPort", "44"]
        workingDir: /scripts
        env:
        - name: AES_KEY_B64
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: aes-secret
              optional: true
        volumeMounts:
        - name: config-volume
          mountPath: /scripts
      volumes:
        - name: config-volume
          configMap:
            name: {{ $.Release.Name }}-pwsh-scripts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-client
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-client
  serviceName: ping-client
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-client
    spec:
      containers:
      - name: {{ $.Release.Name }}-client
        image: mcr.microsoft.com/powershell:latest
        command: ["/bin/pwsh"]
        args: 
          - -Command
          - | 
            $PSVersionTable
            $startTime = Get-Date
            $hostname = Invoke-Expression -Command 'hostname'
            $checkMsg = "${startTime}: ${hostname}@$($PSVersionTable.Platform)"
            $listenPort = Get-Random -Minimum 11000 -Maximum 11999
            while ( $true ) 
            { 
                Start-Sleep $((60 - (Get-Date | % Second)) % 15 )
                $checkMsg = ./latency-check.ps1 `
                    -Message "$checkMsg" `
                    -SendAddress {{ $.Release.Name }}-server `
                    -SendPort 44 `
                    -ListenPort $listenPort
                Start-Sleep 1
                $checkMsg
            }
        workingDir: /scripts
        env:
        - name: AES_KEY_B64
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: aes-secret
              optional: true
        volumeMounts:
        - name: config-volume
          mountPath: /scripts
      volumes:
        - name: config-volume
          configMap:
            name: {{ $.Release.Name }}-pwsh-scripts
---
# Google helm create secret if not exists
# found https://stackoverflow.com/a/61715870/2535649
# links to https://github.com/sankalp-r/helm-charts-examples/blob/main/sample_chart/templates/_helpers.tpl
kind: Secret
apiVersion: v1
metadata:
  name: aes-secret
data:
  {{- $secret := lookup "v1" "Secret" .Release.Namespace "aes-secret" -}}
  {{- if $secret -}} {{/*                        Reusing existing password if secret was found... */}}
  secretkey: {{ $secret.data.secretkey }}
  {{- else -}} {{/*                               ... otherwise, generate a random key.      */}}
  secretkey: {{ randAlphaNum 32 | b64enc | b64enc }}
  {{- end -}}
